apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: openshift-gitops-otp-argocd-application-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: custom-argocd-cluster-argocd-application-controller
subjects:
- kind: ServiceAccount
  name: openshift-gitops-otp-argocd-application-controller
  namespace: openshift-gitops
