apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: itz-deployer-operator
    app.kubernetes.io/managed-by: kustomize
  name: controller-manager-metrics-monitor
  namespace: openshift-operators
spec:
  endpoints:
    - path: /metrics
      port: https
      scheme: https
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        caFile: /etc/prometheus/configmaps/serving-certs-ca-bundle/service-ca.crt
        # UPDATE THIS to match the new shortened service name
        serverName: itz-deployer-operator-metrics-service.openshift-operators.svc
  selector:
    matchLabels:
      # Ensure these labels match what is in your shortened metrics_service.yaml
      control-plane: controller-manager
