apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cluster-service-versions-reader
  namespace: openshift-operators
rules:
  - apiGroups:
      - operators.coreos.com
    resources:
      - clusterserviceversions
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: subscriptions-manager
  namespace: openshift-operators
rules:
  - apiGroups:
      - operators.coreos.com
    resources:
      - subscriptions
    verbs:
      - create
      - get
      - list
      - watch
      - update
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-role
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["argocds", "applications"]
    verbs: ["create", "get", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tekton-tasks-reader
rules:
  - apiGroups:
      - tekton.dev
    resources:
      - tasks
    verbs:
      - get
